name: JazzX
 
on:
  push:
    branches:
      - master
 
permissions:
  contents: read
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests jinja2
          if [ -f Requirements/requirements.txt ]; then pip install -r Requirements/requirements.txt; fi
 
      - name: Test with pytest
        run: pytest API_Requests/Tests/test_get_request.py -v -s --log-cli-level=INFO


